apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-service-a
spec:
  replicas: 2
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: hello-service-a
  template:
    metadata:
      labels:
        app: hello-service-a
    spec:
      containers:
        - image: shamsmali/hello-service-a:1.0.1
          name: hello-service-a
          ports:
            - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: hello-service-a-service
spec:
  selector:
    app.kubernetes.io/name: hello-service-a
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9000